# Generated by Django 3.1.14 on 2023-11-26 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tesla', models.CharField(max_length=200)),
                ('GM', models.CharField(max_length=200)),
                ('Ford', models.CharField(max_length=200)),
            ],
        ),
    ]
